services:
  ci:
    build: .
    ports:
      - "5173:5173"  # Website port
      - "8080:8080"  # Backend port
      - "9222:9222"  # Chrome debugging port
      - "5900:5900"  # VNC port
      - "6080:6080"  # noVNC web-based access
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11 socket for GUI
    environment:
      - DISPLAY=:99  # Use Xvfb display
    # Use privileged mode to allow proper rendering
    privileged: true
    # Set shared memory size to avoid Chrome crashes
    shm_size: '2gb'
