name: Go Test on Release

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.18'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Load .env file
        run: |
          if [ -f .env ]; then
            export $(cat .env | xargs)
          fi
          echo "secret_key_for_hash="MonishPleaseEnterThis--0098" >> .env
          echo "encryption_key="my16dchbsdbebciuhfhqhThhhhhhhhhh" >> .env



      - name: Run tests
        run: go test ./...
        env:
          GO111MODULE: "on"
